BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[EDC_RESPONSAVEL] (
    [id] INT NOT NULL IDENTITY(1,1),
    [cpf] VARCHAR(11) NOT NULL,
    [email] VARCHAR(255),
    [senhaHash] VARCHAR(255) NOT NULL,
    [ativo] BIT NOT NULL CONSTRAINT [EDC_RESPONSAVEL_ativo_df] DEFAULT 1,
    [criadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_criadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    [atualizadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_atualizadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_RESPONSAVEL_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_RESPONSAVEL_cpf_key] UNIQUE NONCLUSTERED ([cpf])
);

-- CreateTable
CREATE TABLE [dbo].[EDC_RESPONSAVEL_ALUNO] (
    [id] INT NOT NULL IDENTITY(1,1),
    [responsavelId] INT NOT NULL,
    [alunoPesCod] INT NOT NULL,
    [vinculadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_ALUNO_vinculadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_RESPONSAVEL_ALUNO_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_RESPONSAVEL_ALUNO_responsavelId_alunoPesCod_key] UNIQUE NONCLUSTERED ([responsavelId],[alunoPesCod])
);

-- CreateTable
CREATE TABLE [dbo].[EDC_PUSH_TOKEN] (
    [id] NVARCHAR(1000) NOT NULL,
    [userId] INT NOT NULL,
    [token] NVARCHAR(1000) NOT NULL,
    [platform] NVARCHAR(1000) NOT NULL,
    [deviceId] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [EDC_PUSH_TOKEN_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [lastUsedAt] DATETIME2 NOT NULL CONSTRAINT [EDC_PUSH_TOKEN_lastUsedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_PUSH_TOKEN_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_PUSH_TOKEN_token_key] UNIQUE NONCLUSTERED ([token])
);

-- CreateTable
CREATE TABLE [dbo].[EDC_PRESENCA_EVENTO] (
    [id] NVARCHAR(1000) NOT NULL,
    [eventId] NVARCHAR(1000) NOT NULL,
    [alunoId] NVARCHAR(1000) NOT NULL,
    [tipo] NVARCHAR(1000) NOT NULL,
    [ocorridoEm] DATETIME2 NOT NULL,
    [recebidoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_PRESENCA_EVENTO_recebidoEm_df] DEFAULT CURRENT_TIMESTAMP,
    [leitorId] NVARCHAR(1000),
    CONSTRAINT [EDC_PRESENCA_EVENTO_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_PRESENCA_EVENTO_eventId_key] UNIQUE NONCLUSTERED ([eventId])
);

-- CreateTable
CREATE TABLE [dbo].[EDC_NOTIFICACAO] (
    [id] NVARCHAR(1000) NOT NULL,
    [userId] INT NOT NULL,
    [eventoId] NVARCHAR(1000) NOT NULL,
    [titulo] NVARCHAR(1000) NOT NULL,
    [corpo] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL CONSTRAINT [EDC_NOTIFICACAO_status_df] DEFAULT 'pendente',
    [tentativas] INT NOT NULL CONSTRAINT [EDC_NOTIFICACAO_tentativas_df] DEFAULT 0,
    [ultimoErro] NVARCHAR(1000),
    [enviadaEm] DATETIME2,
    [lidaEm] DATETIME2,
    [criadaEm] DATETIME2 NOT NULL CONSTRAINT [EDC_NOTIFICACAO_criadaEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_NOTIFICACAO_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [EDC_RESPONSAVEL_ALUNO_alunoPesCod_idx] ON [dbo].[EDC_RESPONSAVEL_ALUNO]([alunoPesCod]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [EDC_PUSH_TOKEN_userId_idx] ON [dbo].[EDC_PUSH_TOKEN]([userId]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [EDC_PRESENCA_EVENTO_alunoId_ocorridoEm_idx] ON [dbo].[EDC_PRESENCA_EVENTO]([alunoId], [ocorridoEm]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [EDC_NOTIFICACAO_userId_criadaEm_idx] ON [dbo].[EDC_NOTIFICACAO]([userId], [criadaEm]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [EDC_NOTIFICACAO_status_idx] ON [dbo].[EDC_NOTIFICACAO]([status]);

-- AddForeignKey
ALTER TABLE [dbo].[EDC_RESPONSAVEL_ALUNO] ADD CONSTRAINT [EDC_RESPONSAVEL_ALUNO_responsavelId_fkey] FOREIGN KEY ([responsavelId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EDC_PUSH_TOKEN] ADD CONSTRAINT [EDC_PUSH_TOKEN_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EDC_NOTIFICACAO] ADD CONSTRAINT [EDC_NOTIFICACAO_eventoId_fkey] FOREIGN KEY ([eventoId]) REFERENCES [dbo].[EDC_PRESENCA_EVENTO]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EDC_NOTIFICACAO] ADD CONSTRAINT [EDC_NOTIFICACAO_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH

