
CREATE TABLE [dbo].[EDU_TIPO_OCORRENCIA_ALUNO](
	[TIPO_OCORRENCIA_COD] [int] IDENTITY(1,1) NOT NULL,
	[TPO_DESCRICAO] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[TIPO_OCORRENCIA_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [dbo].[EDU_ALUNO_OCORRENCIA](
	[OCORRENCIA_COD] [int] IDENTITY(1,1) NOT NULL,
	[AOC_DT_OCORRENCIA] [datetime] NULL,
	[TIPO_OCORRENCIA_COD] [int] NULL,
	[AOC_TITULO] [varchar](100) NULL,
	[AOC_DESCRICAO] [varchar](1000) NULL,
	[AOC_ANO_LETIVO] [int] NULL,
	[ESC_COD] [int] NULL,
	[TMA_COD] [int] NULL,
	[TMH_COD] [int] NULL,
	[PES_COD_PROFESSOR] [int] NULL,
	[AOC_EXIGIR_CONHECIMENTO] [bit] NULL,
	[AOC_RESP_CIENTE] [bit] NULL,
	[AOC_DT_CIENCIA_RESP] [datetime] NULL,
	[USR_CODIGO_RESP] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OCORRENCIA_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EDU_ALUNO_OCORRENCIA] ADD  DEFAULT ((0)) FOR [AOC_RESP_CIENTE]
GO

ALTER TABLE [dbo].[EDU_ALUNO_OCORRENCIA]  WITH CHECK ADD FOREIGN KEY([ESC_COD])
REFERENCES [dbo].[EDU_ESCOLA] ([ESC_COD])
GO

ALTER TABLE [dbo].[EDU_ALUNO_OCORRENCIA]  WITH CHECK ADD FOREIGN KEY([TIPO_OCORRENCIA_COD])
REFERENCES [dbo].[EDU_TIPO_OCORRENCIA_ALUNO] ([TIPO_OCORRENCIA_COD])
GO

ALTER TABLE [dbo].[EDU_ALUNO_OCORRENCIA]  WITH CHECK ADD FOREIGN KEY([TMA_COD])
REFERENCES [dbo].[EDU_TURMA] ([TMA_COD])
GO

ALTER TABLE [dbo].[EDU_ALUNO_OCORRENCIA]  WITH CHECK ADD FOREIGN KEY([TMH_COD])
REFERENCES [dbo].[EDU_TURMA_ALUNO] ([TMH_COD])
GO

CREATE TABLE [dbo].[EDU_AVISOS](
	[AVI_COD] [int] IDENTITY(1,1) NOT NULL,
	[CAR_COD] [int] NULL,
	[TODA_REDE] [char](1) NULL,
	[DATA_INICIO] [datetime] NULL,
	[DATA_FIM] [datetime] NULL,
	[STATUS_COD] [int] NULL,
	[AVISO] [varchar](max) NULL,
	[IMAGEM] [varbinary](max) NULL,
	[USR_CODIGO] [int] NULL,
	[DATA_CRIACAO] [datetime] NULL,
	[DATA_ALTERACAO] [datetime] NULL,
	[ESC_COD] [int] NULL,
	[CUR_COD] [varchar](50) NULL,
	[TITULO] [varchar](100) NULL,
	[EDU_CONECTA] [char](1) NULL,
	[STATUS_CALCULADO]  AS (case when [EDU_AVISOS].[DATA_INICIO]>getdate() then (1) when getdate()>=[EDU_AVISOS].[DATA_INICIO] AND getdate()<=[EDU_AVISOS].[DATA_FIM] then (2) when [EDU_AVISOS].[DATA_FIM]<getdate() then (3) else (3) end),
 CONSTRAINT [EDU_AVISOS_PKEY] PRIMARY KEY CLUSTERED 
(
	[AVI_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EDU_AVISOS]  WITH CHECK ADD  CONSTRAINT [EDU_AVISOS_FK_FR_USUA_5E9DDE82] FOREIGN KEY([USR_CODIGO])
REFERENCES [dbo].[FR_USUARIO] ([USR_CODIGO])
GO

ALTER TABLE [dbo].[EDU_AVISOS] CHECK CONSTRAINT [EDU_AVISOS_FK_FR_USUA_5E9DDE82]
GO

ALTER TABLE [dbo].[EDU_AVISOS]  WITH CHECK ADD  CONSTRAINT [EDU_AVISOS_FK_GER_CAR_19980126] FOREIGN KEY([CAR_COD])
REFERENCES [dbo].[GER_CARGO] ([CAR_COD])
GO

ALTER TABLE [dbo].[EDU_AVISOS] CHECK CONSTRAINT [EDU_AVISOS_FK_GER_CAR_19980126]
GO


CREATE TABLE [dbo].[EDC_TIPO_SOLICITACAO](
	[TIP_COD] [int] NOT NULL,
	[TIP_DESCRICAO] [varchar](30) NOT NULL,
	[TIP_ATIVO] [varchar](1) NULL,
	[TIP_INF_ADICIONAL] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[TIP_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EDC_TIPO_SOLICITACAO] ADD  DEFAULT ('S') FOR [TIP_ATIVO]
GO



INSERT INTO [EDC_TIPO_SOLICITACAO] 
    (TIP_COD, TIP_DESCRICAO, TIP_ATIVO)
VALUES
    (1,'Cadastro de Portador','S'),
    (2,	'Alteração Cadastral'	,'S')

CREATE TABLE [dbo].[EDC_SOLICITACAO](
	[SOL_COD] [int] IDENTITY(1,1) NOT NULL,
	[USR_COD] [int] NOT NULL,
	[SOL_TIP] [tinyint] NOT NULL,
	[SOL_DT] [datetime] NOT NULL,
	[SOL_STATUS] [char](1) NOT NULL,
	[SOL_DADOS] [nvarchar](max) NULL,
	[PES_COD_ALUNO] [int] NOT NULL,
 CONSTRAINT [PK_EDC_SOLICITACAO] PRIMARY KEY CLUSTERED 
(
	[SOL_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EDC_SOLICITACAO] ADD  CONSTRAINT [DF_EDC_SOL_DT]  DEFAULT (getdate()) FOR [SOL_DT]
GO

ALTER TABLE [dbo].[EDC_SOLICITACAO] ADD  CONSTRAINT [DF_EDC_SOL_STATUS]  DEFAULT ('P') FOR [SOL_STATUS]
GO

ALTER TABLE [dbo].[EDC_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [CHK_SOL_STATUS] CHECK  (([SOL_STATUS]='R' OR [SOL_STATUS]='A' OR [SOL_STATUS]='P'))
GO

ALTER TABLE [dbo].[EDC_SOLICITACAO] CHECK CONSTRAINT [CHK_SOL_STATUS]
GO
CREATE TABLE [dbo].[EDU_AVISOS_ESCOLAS](
	[AVE_COD] [int] IDENTITY(1,1) NOT NULL,
	[AVI_COD] [int] NULL,
	[ESC_COD] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[AVE_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EDU_AVISOS_ESCOLAS]  WITH CHECK ADD FOREIGN KEY([AVI_COD])
REFERENCES [dbo].[EDU_AVISOS] ([AVI_COD])
GO

ALTER TABLE [dbo].[EDU_AVISOS_ESCOLAS]  WITH CHECK ADD FOREIGN KEY([ESC_COD])
REFERENCES [dbo].[EDU_ESCOLA] ([ESC_COD])
GO

CREATE TABLE [dbo].[EDU_AVISOS_SEGMENTO](
	[ACU_COD] [int] IDENTITY(1,1) NOT NULL,
	[AVI_COD] [int] NULL,
	[CUR_COD] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACU_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('dbo.EDC_AUTORIZACOES', 'U') IS NULL
CREATE TABLE EDC_AUTORIZACOES (
    AUT_COD               INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    AUT_TITULO            NVARCHAR(255) NULL,
    AUT_DESCRICAO         NVARCHAR(MAX) NULL,
    AUT_TIPO_SOLICITACAO  CHAR(1) NULL,            -- 'A' = aprovação, 'P' = presença
    AUT_DT                DATETIME2 NOT NULL DEFAULT GETDATE(),
    CUR_COD               NVARCHAR(50) NULL,
    AUT_ESC_COD           NVARCHAR(50) NULL,
    AUT_TMA_COD           INT NULL
);
GO

IF OBJECT_ID('dbo.EDC_RESPOSTAS_AUTORIZACAO', 'U') IS NULL
CREATE TABLE EDC_RESPOSTAS_AUTORIZACAO (
    RA_ID             INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    RA_AUT_COD        INT NOT NULL,
    RA_PES_COD_ALUNO  INT NOT NULL,
    RA_RESPONSAVEL    NVARCHAR(255) NULL,
    RA_RESPOSTA       NVARCHAR(50) NULL,
    TMH_COD           INT NULL,
    RA_DT_RESPOSTA    DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

IF OBJECT_ID('dbo.EDC_ANEXO_SOLICITACAO', 'U') IS NULL
CREATE TABLE EDC_ANEXO_SOLICITACAO (
    ANE_COD       INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    SOL_COD       INT NOT NULL,
    ANE_NOME      NVARCHAR(255) NULL,
    ANE_EXTENSAO  NVARCHAR(20) NULL,
    ANE_ARQUIVO   VARBINARY(MAX) NULL
);
GO