/*
 * 03_edc_tables.sql
 *
 * Tabelas próprias do app (EDC_*) gerenciadas via Prisma. Recopia
 * `prisma/migrations-manual/001_create_edc_tables.sql` +
 * `002_password_reset.sql` em forma idempotente pra o seed Docker.
 */
USE EDU_CORURIPE_M5_DEV;
GO

IF OBJECT_ID('dbo.EDC_RESPONSAVEL', 'U') IS NULL
CREATE TABLE [dbo].[EDC_RESPONSAVEL] (
    [id] INT NOT NULL IDENTITY(1,1),
    [cpf] VARCHAR(11) NOT NULL,
    [email] VARCHAR(255),
    [senhaHash] VARCHAR(255) NOT NULL,
    [ativo] BIT NOT NULL CONSTRAINT [EDC_RESPONSAVEL_ativo_df] DEFAULT 1,
    [criadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_criadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    [atualizadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_atualizadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_RESPONSAVEL_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_RESPONSAVEL_cpf_key] UNIQUE NONCLUSTERED ([cpf])
);
GO

IF OBJECT_ID('dbo.EDC_RESPONSAVEL_ALUNO', 'U') IS NULL
CREATE TABLE [dbo].[EDC_RESPONSAVEL_ALUNO] (
    [id] INT NOT NULL IDENTITY(1,1),
    [responsavelId] INT NOT NULL,
    [alunoPesCod] INT NOT NULL,
    [vinculadoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_RESPONSAVEL_ALUNO_vinculadoEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_RESPONSAVEL_ALUNO_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_RESPONSAVEL_ALUNO_responsavelId_alunoPesCod_key] UNIQUE NONCLUSTERED ([responsavelId],[alunoPesCod])
);
GO

IF OBJECT_ID('dbo.EDC_PUSH_TOKEN', 'U') IS NULL
CREATE TABLE [dbo].[EDC_PUSH_TOKEN] (
    [id] NVARCHAR(1000) NOT NULL,
    [userId] INT NOT NULL,
    [token] NVARCHAR(450) NOT NULL,
    [platform] NVARCHAR(50) NOT NULL,
    [deviceId] NVARCHAR(100),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [EDC_PUSH_TOKEN_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [lastUsedAt] DATETIME2 NOT NULL CONSTRAINT [EDC_PUSH_TOKEN_lastUsedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_PUSH_TOKEN_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_PUSH_TOKEN_token_key] UNIQUE NONCLUSTERED ([token])
);
GO

IF OBJECT_ID('dbo.EDC_PRESENCA_EVENTO', 'U') IS NULL
CREATE TABLE [dbo].[EDC_PRESENCA_EVENTO] (
    [id] NVARCHAR(36) NOT NULL,
    [eventId] NVARCHAR(36) NOT NULL,
    [alunoId] NVARCHAR(50) NOT NULL,
    [tipo] NVARCHAR(20) NOT NULL,
    [ocorridoEm] DATETIME2 NOT NULL,
    [recebidoEm] DATETIME2 NOT NULL CONSTRAINT [EDC_PRESENCA_EVENTO_recebidoEm_df] DEFAULT CURRENT_TIMESTAMP,
    [leitorId] NVARCHAR(100),
    CONSTRAINT [EDC_PRESENCA_EVENTO_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [EDC_PRESENCA_EVENTO_eventId_key] UNIQUE NONCLUSTERED ([eventId])
);
GO

IF OBJECT_ID('dbo.EDC_NOTIFICACAO', 'U') IS NULL
CREATE TABLE [dbo].[EDC_NOTIFICACAO] (
    [id] NVARCHAR(36) NOT NULL,
    [userId] INT NOT NULL,
    [eventoId] NVARCHAR(36) NOT NULL,
    [titulo] NVARCHAR(255) NOT NULL,
    [corpo] NVARCHAR(500) NOT NULL,
    [status] NVARCHAR(20) NOT NULL CONSTRAINT [EDC_NOTIFICACAO_status_df] DEFAULT 'pendente',
    [tentativas] INT NOT NULL CONSTRAINT [EDC_NOTIFICACAO_tentativas_df] DEFAULT 0,
    [ultimoErro] NVARCHAR(500),
    [enviadaEm] DATETIME2,
    [lidaEm] DATETIME2,
    [criadaEm] DATETIME2 NOT NULL CONSTRAINT [EDC_NOTIFICACAO_criadaEm_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_NOTIFICACAO_pkey] PRIMARY KEY CLUSTERED ([id])
);
GO

IF OBJECT_ID('dbo.EDC_PASSWORD_RESET', 'U') IS NULL
CREATE TABLE [dbo].[EDC_PASSWORD_RESET] (
    [id] NVARCHAR(36) NOT NULL,
    [responsavelId] INT NOT NULL,
    [codeHash] VARCHAR(255) NOT NULL,
    [emailEnviado] VARCHAR(255) NOT NULL,
    [tentativas] INT NOT NULL CONSTRAINT [EDC_PASSWORD_RESET_tentativas_df] DEFAULT 0,
    [expiresAt] DATETIME2 NOT NULL,
    [usedAt] DATETIME2,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [EDC_PASSWORD_RESET_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [EDC_PASSWORD_RESET_pkey] PRIMARY KEY CLUSTERED ([id])
);
GO

-- Indexes (idempotentes)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_RESPONSAVEL_ALUNO_alunoPesCod_idx' AND object_id = OBJECT_ID('dbo.EDC_RESPONSAVEL_ALUNO'))
    CREATE NONCLUSTERED INDEX [EDC_RESPONSAVEL_ALUNO_alunoPesCod_idx] ON [dbo].[EDC_RESPONSAVEL_ALUNO]([alunoPesCod]);
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_PUSH_TOKEN_userId_idx' AND object_id = OBJECT_ID('dbo.EDC_PUSH_TOKEN'))
    CREATE NONCLUSTERED INDEX [EDC_PUSH_TOKEN_userId_idx] ON [dbo].[EDC_PUSH_TOKEN]([userId]);
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_PRESENCA_EVENTO_alunoId_ocorridoEm_idx' AND object_id = OBJECT_ID('dbo.EDC_PRESENCA_EVENTO'))
    CREATE NONCLUSTERED INDEX [EDC_PRESENCA_EVENTO_alunoId_ocorridoEm_idx] ON [dbo].[EDC_PRESENCA_EVENTO]([alunoId], [ocorridoEm]);
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_NOTIFICACAO_userId_criadaEm_idx' AND object_id = OBJECT_ID('dbo.EDC_NOTIFICACAO'))
    CREATE NONCLUSTERED INDEX [EDC_NOTIFICACAO_userId_criadaEm_idx] ON [dbo].[EDC_NOTIFICACAO]([userId], [criadaEm]);
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_NOTIFICACAO_status_idx' AND object_id = OBJECT_ID('dbo.EDC_NOTIFICACAO'))
    CREATE NONCLUSTERED INDEX [EDC_NOTIFICACAO_status_idx] ON [dbo].[EDC_NOTIFICACAO]([status]);
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDC_PASSWORD_RESET_responsavelId_createdAt_idx' AND object_id = OBJECT_ID('dbo.EDC_PASSWORD_RESET'))
    CREATE NONCLUSTERED INDEX [EDC_PASSWORD_RESET_responsavelId_createdAt_idx] ON [dbo].[EDC_PASSWORD_RESET]([responsavelId], [createdAt]);
GO

-- Foreign keys (idempotentes)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'EDC_RESPONSAVEL_ALUNO_responsavelId_fkey')
    ALTER TABLE [dbo].[EDC_RESPONSAVEL_ALUNO] ADD CONSTRAINT [EDC_RESPONSAVEL_ALUNO_responsavelId_fkey]
    FOREIGN KEY ([responsavelId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'EDC_PUSH_TOKEN_userId_fkey')
    ALTER TABLE [dbo].[EDC_PUSH_TOKEN] ADD CONSTRAINT [EDC_PUSH_TOKEN_userId_fkey]
    FOREIGN KEY ([userId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'EDC_NOTIFICACAO_eventoId_fkey')
    ALTER TABLE [dbo].[EDC_NOTIFICACAO] ADD CONSTRAINT [EDC_NOTIFICACAO_eventoId_fkey]
    FOREIGN KEY ([eventoId]) REFERENCES [dbo].[EDC_PRESENCA_EVENTO]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'EDC_NOTIFICACAO_userId_fkey')
    ALTER TABLE [dbo].[EDC_NOTIFICACAO] ADD CONSTRAINT [EDC_NOTIFICACAO_userId_fkey]
    FOREIGN KEY ([userId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'EDC_PASSWORD_RESET_responsavelId_fkey')
    ALTER TABLE [dbo].[EDC_PASSWORD_RESET] ADD CONSTRAINT [EDC_PASSWORD_RESET_responsavelId_fkey]
    FOREIGN KEY ([responsavelId]) REFERENCES [dbo].[EDC_RESPONSAVEL]([id]) ON DELETE CASCADE ON UPDATE CASCADE;
GO

PRINT '✓ Tabelas EDC_* aplicadas.';
